name: GitHub App token
author: RVU SRE (sre@rvu.co.uk)
description: Run a GitHub Action as a GitHub App instead of using secrets.GITHUB_TOKEN or a personal access token.
inputs:
  app_id:
    description: ID of the GitHub App.
    required: true
  private_key:
    description: Private key of the GitHub App (can be Base64 encoded).
    required: true
  org:
    description: The name of the Organization for which we will retrieve an installation token.
    required: true
outputs:
  token:
    description: An installation token for the GitHub App on the requested organization.
runs:
  using: node12
  main: dist/index.js
branding:
  icon: unlock
  color: gray-dark
